version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ./hms_backend
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    volumes:
      - ./hms_backend:/app/hms_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/hms_db
      DJANGO_SECRET_KEY: change-me
      DEBUG: 'True'
    depends_on:
      - db

volumes:
  db_data:
